version: '3'
services:
  www:
    depends_on: 
      - db
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443

    networks:
      - lamp-docker
  db:
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=Jts20230927
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=pwssword
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes: 
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
